package com.pscarpellini.frontend.enums.designsystem

enum class IconesEnum(
    val caminhoDoIcone: String,
    val caminhoDoIconePreenchido: String? = null,
) {
    LUMEN_COLORIDA("/static/logos/logo_icone.svg"),
    LUMEN_BRANCA("/static/logos/logo_icone_branca.svg"),
    LUMEN_PRETA("/static/logos/logo_icone_preta.svg"),

    //  ICONES GERAIS
    ADICIONAR("/static/icons/adicionar.svg"),
    ADICIONAR_CIRCULO("/static/icons/adicionar_circulo.svg"),
    AJUDA("/static/icons/ajuda.svg"),
    ARROW_DOWN("/static/icons/arrow_down.svg"),
    ARROW_LEFT("/static/icons/arrow_left.svg"),
    ARROW_RIGHT("/static/icons/arrow_right.svg"),
    ARROW_UP("/static/icons/arrow_up.svg"),
    BULLET_LISTA("/static/icons/bullet_lista.svg"),
    BUSCAR("/static/icons/buscar.svg"),
    CALENDARIO("/static/icons/calendario.svg"),
    CARTEIRA("/static/icons/carteira.svg"),
    CHECK("/static/icons/check.svg"),
    CHEVRON_DOWN("/static/icons/chevron_down.svg"),
    CHEVRON_LEFT("/static/icons/chevron_left.svg"),
    CHEVRON_RIGHT("/static/icons/chevron_right.svg"),
    CHEVRON_UP("/static/icons/chevron_up.svg"),
    CLOSE("/static/icons/close.svg"),
    COMPARTILHAR("/static/icons/compartilhar.svg"),
    CONFIGURACOES("/static/icons/configuracoes.svg"),
    COPIA("/static/icons/copiar.svg"),
    CRONOMETRO("/static/icons/cronometro.svg"),
    EDITAR("/static/icons/editar.svg"),
    EMAIL("/static/icons/email.svg"),
    EXTRATO("/static/icons/extrato.svg"),
    FILTRO("/static/icons/filtro.svg"),
    GRAFICO_TENDENCIA("/static/icons/grafico_tendencia.svg"),
    INFO("/static/icons/info.svg"),
    LOADER("/static/icons/loader.svg"),
    LOGOUT("/static/icons/logout.svg"),
    MAIS("/static/icons/mais.svg"),
    MENU("/static/icons/menu.svg"),
    MINI_ARROW_LEFT("/static/icons/mini_arrow_right.svg"),
    NOTIFICACOES("/static/icons/notificacoes.svg"),
    OLHO_ABERTO("/static/icons/olho_aberto.svg"),
    OLHO_FECHADO("/static/icons/olho_fechado.svg"),
    PLAY_CIRCULO("/static/icons/play_circulo.svg"),
    PREMIUM("/static/icons/premium.svg"),
    PROMOCAO("/static/icons/promocao.svg"),
    REMOVER_CIRCULO("/static/icons/remover_circulo.svg"),
    TELEFONE("/static/icons/telefone.svg"),
    USUARIO("/static/icons/usuario.svg"),
    WHATSAPP("/static/icons/whatsapp.svg"),

    //  ICONES DO MENU PRINCIPAL
    APP("/static/icons/menu/app.svg", caminhoDoIconePreenchido = "/static/icons/menu/app_preenchido.svg"),
    BUSCA("/static/icons/menu/busca.svg"),
    CARRINHO("/static/icons/menu/carrinho.svg", caminhoDoIconePreenchido = "/static/icons/menu/carrinho_preenchido.svg"),
    DOCUMENTO("/static/icons/menu/documento.svg"),
    DOUBLE_ARROW("/static/icons/menu/double_arrow.svg"),
    HISTORICO("/static/icons/menu/historico.svg", caminhoDoIconePreenchido = "/static/icons/menu/historico_preenchido.svg"),
    HOME("/static/icons/menu/home.svg", caminhoDoIconePreenchido = "/static/icons/menu/home_preenchido.svg"),
    PRECO("/static/icons/menu/preco.svg", caminhoDoIconePreenchido = "/static/icons/menu/preco_preenchido.svg"),
    USUARIOS("/static/icons/menu/usuarios.svg", caminhoDoIconePreenchido = "/static/icons/menu/usuarios_preenchido.svg"),
}